# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [main,develop]
  pull_request:
    branches: [main,develop]



jobs:
  build-push-update-gitops:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set variables
        id: vars
        shell: bash
        run: |
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${GITHUB_SHA:0:7}-$GITHUB_RUN_ID" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Image
        run: |
          mvn -B deploy \
          -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/marknazareno/spring-boot-demo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/marknazareno/spring-boot-demo:${{ env.IMAGE_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Checkout GitOps File
        uses: actions/checkout@v2
        with:
          repository: marknazareno/gitops-apps-prod
          path: gitops-apps-prod
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Set up yq
        uses: mikefarah/yq@v4.9.3
        with:
          cmd: yq eval '.images[0].newTag="${{ env.IMAGE_TAG }}"' -i gitops-apps-prod/spring-boot-demo/kustomization.yaml

      - name: commit updated yaml
        working-directory: ./gitops-apps-prod
        run: |
          git config user.name github-actions
          git config user.email github-actions@marknazareno.com
          git add .
          git commit -m "update spring-boot-demo to ${{ env.IMAGE_TAG }}"
          git push
